
pip: python/requirements.txt

npm: ['package-lock.json','package.json']

dependencies: ['package-lock.json','package.json','python/requirements.txt']

github_actions: .github/workflows/*

dependabot: .github/dependabot.yml

gitignore: '*.gitignore'

javascript: '*.js'

python: '*.py'

html: '*.html'

css: '*.css'

json: '*.json'

shell: '*.sh'

yml: '*.yml'

markdown: ['*.md', '*.markdown']

github: .github/*

resources: ['resources/*','src/res/*','public/res/*']

image: ['*.jpg', '*.jpeg', '*.png']