# Dependencies
pip: 'python/requirements.txt'
npm: ['package-lock.json','package.json']

# Frameworks
next.js: 'next.config.js'


# Github
labels: ['.github/labeler.yml', '.github/workflows/labeler.yml']
github_actions: '.github/workflows/*'
dependabot: '.github/dependabot.yml'
gitignore: '**/*.gitignore'
github: '.github/*'


# Languages
javascript: ['**/*.js', '**/*.jsx']
react: '**/*.jsx'
python: '**/*.py'
html: '**/*.html'
css: '**/*.css'
json: '**/*.json'
shell: '**/*.sh'
yml: '**/*.yml'
markdown: ['**/*.md', '**/*.markdown']
image: ['*.jpg', '*.jpeg', '*.png']

# Directories
components: 'components/**/*'
config: 'config/**/*'
libraries: 'libs/**/*'
pages: 'pages/**/*'
public: 'public/**/*'
styles: 'styles/**/*'