name: Build Website

on:
  push:
  schedule:
  - cron: '0 0 * * *'

env:
  API_GITHUB: ${{ secrets.API_GITHUB }}

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-python@v2
        name: Set up Python 3.8
        with:
          python-version: 3.8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'npm'
      - name: Install Dependencies with Node
        run: npm ci
      - name: Build with Node
        run: npm run build
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
