name: Build Website

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  build-website:
    concurrency:
      group: ${{github.action}}-${{github.head_ref || github.ref}}
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'python/requirements.txt'
      - name: Set up Node 17
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'npm'
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{github.repository}}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}-node-
      - name: Cache Pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-${{github.repository}}-pip-${{hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}-pip-
      - name: Cache Python
        uses: actions/cache@v3
        with:
          path: |
            python/**/__pycache__
          key: ${{runner.os}}-${{github.repository}}-python-${{hashFiles('python/**/*.py')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}-python-
      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: ./.next/cache
          key: ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-nextjs-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-nextjs-${{github.run_id}}-
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-nextjs-
            ${{runner.os}}-${{github.repository}}/-nextjs-
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./cache
          key: ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-${{github.run_id}}-
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-
            ${{runner.os}}-${{github.repository}}/-cache-
      - name: Install Python Dependencies
        run: python -m pip install -r python/requirements.txt
      - name: Install Javascript Dependencies
        run: npm install
      - name: Run Python Build
        run: python ./python/build.py
        env:
          API_GITHUB: ${{ secrets.API_GITHUB }}
          # RUN_NUMBER: ${{github.run_number}}
      - name: Run Node Compile
        run: npm run compile
        env:
          API_GITHUB: ${{ secrets.API_GITHUB }}
      - name: Run Python Post Render
        run: python ./python/postrender.py
      - name: Publish to Github Pages
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/
      - name: Run Python Cleanup
        run: python ./python/clean.py
        env:
          RUN_NUMBER: ${{github.run_number}}
