name: Build Website

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
  - cron: '0 */6 * * *'

env:
  NODE_ENV: production
  RUN_NUMBER: ${{github.run_number}}

jobs:
  build-website:
    concurrency:
      group: ${{github.action}}-${{github.head_ref || github.ref}}
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'npm'
      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: ./.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./cache
          key: ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-${{github.run_id}}-
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-
            ${{runner.os}}-${{github.repository}}/-cache-
      - name: Install Node Dependencies
        run: npm install
      - name: Next.js Render
        run: npm run render
        env:
          API_GITHUB: ${{ secrets.API_GITHUB }}
      - name: Publish to Github Pages
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/
