name: Build Website

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
  - cron: '0 9 * * *'


jobs:
  build-website:
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'python/requirements.txt'
      - name: Set up Node 17
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{runner.os}}-${{github.repository}}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}-node-
      - name: Cache Pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-${{github.repository}}-pip-${{hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}-pip-
      - name: Cache Next.js
        uses: actions/cache@v3
        with:
          path: ./.next/cache
          key: ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-nextjs-${{ hashFiles('.git/**')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-nextjs-
            ${{runner.os}}-${{github.repository}}/-nextjs-
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./cache
          key: ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-${{ hashFiles('.git/**')}}
          restore-keys: |
            ${{runner.os}}-${{github.repository}}/${{github.head_ref}}-cache-
            ${{runner.os}}-${{github.repository}}/-cache-
      # - name: Update Pip
      #   run: python -m pip install --upgrade pip
      - name: Install Python Dependencies
        run: python -m pip install -r python/requirements.txt
      - name: Install Javascript Dependencies
        run: npm ci
      - name: Run Python Build
        run: python3 ./python/build.py
        env:
          API_GITHUB: ${{ secrets.API_GITHUB }}
      - name: Run Node Compile
        run: npm run compile
        env:
          API_GITHUB: ${{ secrets.API_GITHUB }}
      - name: Publish to Github Pages
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/
