name: Build Website

on:
  push:
    branches: [main]
  pull_request_target:
  schedule:
    - cron: "23 3 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_ENV: production
  RUN_NUMBER: ${{github.run_number}}

jobs:
  build-website:
    concurrency:
      group: ${{github.action}}-${{github.head_ref || github.ref}}
    name: "Build Website"
    runs-on: ubuntu-latest
    env:
      WAKA_TOKEN: ${{secrets.WAKA_TOKEN}}
      API_GITHUB: ${{secrets.API_GITHUB}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        id: checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          cache: "npm"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Install Node Dependencies
        run: npm i
      - name: Install Python Dependencies
        run: npm run pip
      - name: Run Images Script
        run: npm run images
      - name: Generate CSS Files
        run: npm run css
      - name: Pull WakaTime Data
        run: npm run wakatime
      - name: Pull GitHub Data
        run: npm run github
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        with:
          path: "src/"
      - name: Deploy to Github Pages
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: actions/deploy-pages@v2
