name: Build Website

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
  - cron: '0 */6 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  NODE_ENV: production
  RUN_NUMBER: ${{github.run_number}}

jobs:
  build-website:
    concurrency:
      group: ${{github.action}}-${{github.head_ref || github.ref}}
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: ./cache
          key: CACHE-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            CACHE-${{github.run_id}}
            CACHE-
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Install Node Dependencies
        run: npm i
      - name: Run Python Script
        run: python build.py
        env:
          API_GITHUB: ${{secrets.API_GITHUB}}
          WAKA_TOKEN: ${{secrets.WAKA_TOKEN}}
      - name: Run Node Script
        run: npm run build
      - name: Add scss to gitignore
        run: echo "*.scss" >> out/.gitignore
      - name: Upload Artifact
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'out/'
      - name: Deploy to GitHub Pages
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: actions/deploy-pages@v2
        
        
