name: Build Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Run Build Script
        run: sh ./build.sh
      - name: Clean Repository
        run: python3 ./python/clean_project.py
      - name: Remove Gitignore
        run: rm .gitignore
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .