name: Build Website

on:
  push:
  schedule:
  - cron: '0 0 * * *'

env:
  API_GITHUB: ${{ secrets.API_GITHUB }}

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - uses: actions/setup-python@v2
        name: Set up Python 3.8
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: ./python/requirements.txt
      - name: Run Build Script
        run: sh ./build.sh
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
