name: Build Website

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
  - cron: '0 */6 * * *'

env:
  NODE_ENV: production
  RUN_NUMBER: ${{github.run_number}}

jobs:
  build-website:
    concurrency:
      group: ${{github.action}}-${{github.head_ref || github.ref}}
    name: "Build Website"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        id: checkout
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          cache: 'npm'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install Python Dependencies
        run: npm run pip
      - name: Run Images Script
        run: npm run images
      - name: Run CSS Script
        run: npm run css
      - name: Run Wakatime Script
        run: npm run wakatime
      - name: Run Projects Script
        run: npm run projects
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        with:
          path: 'src/'
      - name: Deploy to Github Pages
        if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        uses: actions/deploy-pages@v2
