name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - uses: actions/setup-python@v3
        name: Set up Python 3.8
        with:
          python-version: 3.8
      - name: Run Build Script
        run: sh ./build.sh
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/