name: "Custom Actions"

on:
  issue_comment:
    types: [created]
  
permissions:
    pull-requests: write
    contents: write

jobs:
  automerge:
    name: "Automerge"
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.actor == 'LittleTealeaf' && github.event.comment.body == '>automerge')}}
    steps:
      - run: gh pr merge --auto --squash "$PR_URL"
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
